version: '3.8'

services:
  db:
    image: postgres:15
    container_name: izakaya-db
    environment:
      POSTGRES_USER: izakaya
      POSTGRES_PASSWORD: izakaya_pass
      POSTGRES_DB: izakaya_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
